services:
  portainer:
    image: portainer/portainer-ce:2.39.1
    container_name: portainer
    restart: always
    ports:
      - "10.244.10.4:9443:9443"   # HTTPS via ZeroTier only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    command: --admin-password='$$2b$$12$$<bcrypt-hash-redacted>'

volumes:
  portainer_data:
    name: portainer_data
